from dataclasses import dataclass as _dataclass


@_dataclass
class Worklist:
    study_date: str = ""
    study_time: str = ""
    accession_number: str = ""
    institution_name: str = ""
    institution_address: str = ""

    patient_name: str = ""
    patient_id: str = ""
    patient_sex: str = ""
    patient_birthdate: str = ""
    patient_size: str = ""
    patient_weight: str = ""
    patient_address: str = ""

    medical_alerts: str = ""
    contrast_allergies: str = ""
    study_instance_uid: str = ""
    requesting_physician: str = ""

    modality: str = ""
    requested_contrast_agent: str = ""
    scheduled_station_aetitle: str = ""
    scheduled_procedure_step_startdate: str = ""
    scheduled_procedure_step_starttime: str = ""
    scheduled_procedure_step_enddate: str = ""
    scheduled_procedure_step_endtime: str = ""
    scheduled_performing_physician_name: str = ""
    scheduled_procedure_step_description: str = ""
    scheduled_procedure_step_id: str = ""
    scheduled_station_name: str = ""
    scheduled_procedure_step_location: str = ""
    pre_medication: str = ""
    scheduled_procedure_step_status: str = ""

    def create_sample(self):
        self.study_date = "20180821"
        self.study_time = "095356"
        self.accession_number = "123456"
        self.institution_name = "Clinic A"
        self.institution_address = "contact@clinic.com"

        self.patient_name = "Patient^Name"
        self.patient_id = "001"
        self.patient_sex = "M"
        self.patient_birthdate = "19890815"
        self.patient_size = "1,86"
        self.patient_weight = "110"
        self.patient_address = "patient@patient.com"

        self.medical_alerts = "None"
        self.contrast_allergies = "TANTAL"
        self.study_instance_uid = "1.2.276.0.7230010.3.2.101"
        self.requesting_physician = "Dr Peter"
        self.requested_procedure_description = "Left Leg DSA"

        self.modality = "RF"
        self.requested_contrast_agent = "None"
        self.scheduled_station_aetitle = "FINDSCU"
        self.scheduled_procedure_step_startdate = "20180821"
        self.scheduled_procedure_step_starttime = "102635"
        self.scheduled_procedure_step_enddate = "20180821"
        self.scheduled_procedure_step_endtime = "110000"
        self.scheduled_performing_physician_name = "ROSS"
        self.scheduled_procedure_step_description = "EXAM04"
        self.scheduled_procedure_step_id = "SPD1342"
        self.scheduled_station_name = "CP123"
        self.scheduled_procedure_step_location = "B67F66"
        self.pre_medication = "None"
        self.scheduled_procedure_step_status = "None"
