class Worklist:
    def __init__(self):
        self.study_date = ""
        self.study_time = ""
        self.accession_number = ""
        self.institution_name = ""
        self.institution_address = ""

        self.patient_name = ""
        self.patient_id = ""
        self.patient_sex = ""
        self.patient_birthdate = ""
        self.patient_size = ""
        self.patient_weight = ""
        self.patient_address = ""

        self.medical_alerts = ""
        self.contrast_allergies = ""
        self.study_instance_uid = ""
        self.requesting_physician = ""

        self.modality = ""
        self.requested_contrast_agent = ""
        self.scheduled_station_aetitle = ""
        self.scheduled_procedure_step_startdate = ""
        self.scheduled_procedure_step_starttime = ""
        self.scheduled_procedure_step_enddate = ""
        self.scheduled_procedure_step_endtime = ""
        self.scheduled_performing_physician_name = ""
        self.scheduled_procedure_step_description = ""
        self.scheduled_procedure_step_id = ""
        self.scheduled_station_name = ""
        self.scheduled_procedure_step_location = ""
        self.pre_medication = ""
        self.scheduled_procedure_step_status = ""

    def create_sample(self):
        self.study_date = "20180821"
        self.study_time = "095356"
        self.accession_number = "123456"
        self.institution_name = "Clinic A"
        self.institution_address = "contact@clinic.com"

        self.patient_name = "Patient^Name"
        self.patient_id = "001"
        self.patient_sex = "M"
        self.patient_birthdate = "19890815"
        self.patient_size = "1,86"
        self.patient_weight = "110"
        self.patient_address = "patient@patient.com"

        self.medical_alerts = "None"
        self.contrast_allergies = "TANTAL"
        self.study_instance_uid = "1.2.276.0.7230010.3.2.101"
        self.requesting_physician = "Dr Peter"
        self.requested_procedure_description = "Left Leg DSA"

        self.modality = "RF"
        self.requested_contrast_agent = "None"
        self.scheduled_station_aetitle = "FINDSCU"
        self.scheduled_procedure_step_startdate = "20180821"
        self.scheduled_procedure_step_starttime = "102635"
        self.scheduled_procedure_step_enddate = "20180821"
        self.scheduled_procedure_step_endtime = "110000"
        self.scheduled_performing_physician_name = "ROSS"
        self.scheduled_procedure_step_description = "EXAM04"
        self.scheduled_procedure_step_id = "SPD1342"
        self.scheduled_station_name = "CP123"
        self.scheduled_procedure_step_location = "B67F66"
        self.pre_medication = "None"
        self.scheduled_procedure_step_status = "None"
